### ISSUE TITLE
API does not allow serving files in subdirectories

### ISSUE THREAD

**Issue by bast** [bast/cicero#11]
This may well be a feature but currently this breaks the demo slides.

**Comment by robertodr** [comment]
I cannot manage to serve [this talk](https://github.com/robertodr/talk-spherical-diffuse) even though the markdown file is not in a subdirectory. I get an "Internal Server Error"

**Comment by bast** [comment]
I will look at it now.

**Comment by bast** [comment]
Running the app locally with `python cicero.py` and serving http://0.0.0.0:5000/v1/github/robertodr/talk-spherical-diffuse/master/talk.mkd/remark/ works. Something funny is happening on the server. I am checking it out.

**Comment by bast** [comment]
Problem is solved (problem with your talk, not the issue with subdirectories which is unrelated - therefore I will keep this issue open until then). At the same time http://cicero.xyz migrated to another server. It may take an hour or so to update the DNS servers but say in two hours everything should be stable.

**Comment by robertodr** [comment]
OK thanks! And sorry for cross-posting.

**Comment by bast** [comment]
@robertodr @olemb I am considering changing the API from 
currently /v1/github/namespace/repo/branch/file/remark/
to /v2/remark/github/namespace/repo/branch/file/ (while of course continuing
supporting v1). The advantage would be the possibility to serve
files in subdirectories. The "remark" is currently redundant since
it is the only supported engine. We could drop this redundancy
and "hardcode" cicero to remark. But I am a bit eye-ing at revealjs
but perhaps that falls under YAGNI. Same for GitHub but my plan
is to also allow GitLab and Bitbucket. Long story short what
are your thoughts about /v2/remark/github/namespace/repo/branch/file/?
I want a hackable URL that lives "forever".

**Comment by robertodr** [comment]
I am in favor of this change. But will it be easy for you to make automatic the switch from `remark/github` to `other_engine/other_host` whne the time comes?

**Comment by bast** [comment]
The switch is easy. My worry is more that it may never happen for some reason and then we just carry around a redundantly long URL. But I think it is good to allow room for it. The alternative would be a short v2 API and introduce more engines etc. in later versions of the API. But I don't want to support too many APIs obviously :-)

**Comment by robertodr** [comment]
I guess you can print out the full URL and a shortened version of it.
