### ISSUE TITLE
Local preview broken

### ISSUE THREAD

**Issue by robertodr** [bast/cicero#3]
The local preview works only if the markdown file is in the same directory as the Python scripts:
`python cicero.py -f demo.mkd` 
renders correctly to 0.0.0.0:5000
while:
`python ~/path/to/cicero.py -f my_file.mkd` 
gives an error in the browser.

**Comment by bast** [comment]
We will fix this but the file does not have to sit in the same directory.
I normally use it the other way round (`cicero.py` is in my directory
and the Markdown file is somewhere else) and this works (with full path).
I think it is broken with relative path.

**Comment by olemb** [comment]
I've sent you a pull request which fixes this issue.

**Comment by bast** [comment]
I confirm that it works now. Thanks a lot! Closing this issue.
