### ISSUE TITLE
Reorganize apps with blueprints

### ISSUE THREAD

**Issue by olemb** [bast/cicero#5]
Today we have separate apps for server and preview mode. This leads to duplicate code and makes it impossible to pass config parameters to the Flask contructor based on the command line.

We could fix this by switching to blueprints: http://flask.pocoo.org/docs/0.10/blueprints/

The code would then look something like this:

    server = flask.Blueprint('server')

    @server.route('/')
    def home():
        ...

    def main():
        args = parse_args()

        app = flask.Flask('Cicero',
                          template_folder=paths.TEMPLATE_FOLDER,
                          static_folder=paths.STATIC_FOLDER)

        if args.filename:
            app.config['filename'] = args.filename
            app.register_blueprint(preview)
        else:
            app.register_blueprint(server)

        app.register_blueprint(common)

**Comment by bast** [comment]
Was introduced in #8. Closing.
