### ISSUE TITLE
Does not work with ANSI encoding

### ISSUE THREAD

**Issue by arnfinn** [bast/cicero#54]
I am not sure if it is a big deal, but I get an "Internal Server Error" if the md-file is encoded with ANSI (windows). It is probably only a problem if the file contains special characters (like Norwegian letters). See example below.

With ANSI encoding:
http://cicero.xyz/v2/remark/github/arnfinn/presentasjoner/master/ansi.md

With UTF-8 encoding (the same presentation):
http://cicero.xyz/v2/remark/github/arnfinn/presentasjoner/master/utf8.md

v3 also does not work: http://cicero.xyz/v3/remark/0.14.0/github.com/arnfinn/presentasjoner/master/ansi.md

**Comment by bast** [comment]
Thanks! I will look at it. We better be Windows compliant now :-)

**Comment by arnfinn** [comment]
I found out about this [MS-shit](https://blog.github.com/2018-06-04-github-microsoft/) just after I submitted this issue, so not related:)

**Comment by bast** [comment]
Confirmed. Thanks for the good test case.

**Comment by bast** [comment]
So the local preview is easy to fix but the URL view is more difficult to fix because the URL response tells me that encoding is UTF-8. See also here:
https://cdn.rawgit.com/arnfinn/presentasjoner/623b8f50a220f18753b4418ccb06489b5376c657/ansi.md

Does this look good on your side?

**Comment by arnfinn** [comment]
Looks like this, so I guess not looking good:
![image](https://user-images.githubusercontent.com/136346/40938508-5d1f765a-6842-11e8-88ca-d721fcdd15ab.png)

**Comment by bast** [comment]
Same here. So cicero already receives this with wrong encoding and then it will also show the question mark. But at least it will not crash so I will submit the patch. Local preview seems to work fine (after upcoming patch).
