### ISSUE TITLE
Change slide ratio

### ISSUE THREAD

**Issue by arnfinn** [bast/cicero#55]
I would like to make a 16:9 presentation. Is that possible through Cicero? With Remark it is something like this:
```
var slideshow = remark.create({ ratio: "16:9" });
```

Sidenote: Are there still places you have to use 4:3?

**Comment by bast** [comment]
Cool! I did not know about this. I will look at it.

**Comment by bast** [comment]
I think we should default to 16:9 but offer the option to turn to 4:3.

**Comment by bast** [comment]
Or the other way? Default 4:3 with option for 16:9? @robertodr

**Comment by robertodr** [comment]
I don't have a strong opinion on this. I guess 16:9 is more common than 4:3 nowadays, so should probably be the default?

**Comment by arnfinn** [comment]
I guess keeping 4:3 on `v2` so you do not break old presentations?

**Comment by bast** [comment]
It's good suggestions and I will consider it but I just figured out that you can do it already - undocumented feature. If your talk is called `mytalk.md` you can add a file called `mytalk.conf` which contains:
```
ratio: "16:9"
```
And it will do the right thing :-)

**Comment by arnfinn** [comment]
Works like a charm:) Thanks!

**Comment by bast** [comment]
I will reopen as a reminder to myself to document this better.

**Comment by bast** [comment]
In the latest version this became a non-issue since the configuration can be fully customized using `*.body.html`. Documentation coming up.
