### ISSUE TITLE
suggested license change to AGPL

### ISSUE THREAD

**Issue by bast** [bast/cicero#61]
@robertodr @olemb I would like to suggest changing license to Affero GPL:
https://www.gnu.org/licenses/why-affero-gpl.html

I think this license is more appropriate for programs behind web services.

In particular:
```
The GNU Affero General Public License is a modified version of the ordinary GNU GPL
version 3. It has one added requirement: if you run a modified program on a server
and let other users communicate with it there, your server must also allow them to
download the source code corresponding to the modified version running there.
```

In other words running a web service then equals to distributing the code. I personally care much more about share-alike than permissiveness.

What is your opinion?

**Comment by robertodr** [comment]
I agree it sounds like a better fit for cicero. Be aware that AGPL is based on GPL, not LGPL.

**Comment by bast** [comment]
Just discussed with Ole Martin over lunch and he also supports a switch to AGPL. We think this is the right fit for a SaaS. Cicero is a service, not really a library.

**Comment by bast** [comment]
@arnfinn @christianp @mlouhivu since you have contributed patches to the code under LGPL, I should ask you as well: do you agree to a license change to AGPL?

**Comment by arnfinn** [comment]
YES

**Comment by christianp** [comment]
AGPL isn't my preference, but my contribution was minimal so I'm fine with it.

**Comment by bast** [comment]
Out of curiosity/interest: why not?

**Comment by christianp** [comment]
I'm a live-and-let-live kind of person. I usually go with MIT or Apache.

**Comment by mlouhivu** [comment]
Yes, I'm also fine with the change.

**Comment by bast** [comment]
Thanks everybody!
