### ISSUE TITLE
Replace rawgit with something else

### ISSUE THREAD

**Issue by arnfinn** [bast/cicero#63]
Seems like [rawgit](https://rawgit.com/) is closing down its services.

I get the following page when I try to open one of my [presentations](https://cicero.xyz/v2/remark/github/arnfinn/cicero/master/demo/talk.md/#1):
![image](https://user-images.githubusercontent.com/136346/46808524-db0ca080-cd6c-11e8-9a3a-ece26911f792.png)

**Comment by robertodr** [comment]
Seems one of the suggested services has a migration tool already: https://www.jsdelivr.com/rawgit

**Comment by bast** [comment]
OK that is of course a bad surprise. Hope the presentation is not due today. I will try to fix this ASAP.
