### ISSUE TITLE
Website error at cicero.xyz

### ISSUE THREAD

**Issue by timothyb0912** [bast/cicero#83]
It seems the website certificate may have expired?

I am getting an error when trying to visit previously working links to view my presentations (and share them with others):
`NET::ERR_CERT_DATE_INVALID`.

**Comment by bast** [comment]
Hi Timothy. Sorry for this. I also noticed this only today (and didn't see this issue until today). I plan to fix this tomorrow but this will require a bit of digging in AWS which is managing the certificate.

**Comment by bast** [comment]
Indeed the AWS certificate seems to have expired. Working on renewing this.

**Comment by bast** [comment]
AWS makes it very difficult for me to renew the certificate. I am considering moving the service to a different provider tomorrow. I need this service myself for a presentation on Tue.

I am very sorry for the troubles with it.

**Comment by bast** [comment]
Migration in progress ...

**Comment by bast** [comment]
The service is back. I moved it to different hosting. Apologies for the downtime.

**Comment by timothyb0912** [comment]
@bast no worries, thanks so much for fixing the issue quickly and for maintaining such a useful service.

Have a great week!

**Comment by bast** [comment]
It's nice to know that this is useful. If there is something missing, I am always interested to hear.
